### ISSUE TITLE
Incompatibility with DNF-2.0

### ISSUE THREAD

**Issue by j-mracek** [pnemade/dnf-langpacks#2]
The package is so far incompatible with DNF-2.0 (copr repo rpmsoftwaremanagement/rpm-gitoverlay-1464704925.8089454). See traceback:
[hrom@localhost ~]$ dnf install acpi -v
Loaded plugins: builddep, config-manager, copr, debuginfo-install, download, generate_completion_cache, langpacks, needs-restarting, noroot, playground, protected_packages, repoquery, reposync
Traceback (most recent call last):
  File "/usr/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.5/site-packages/dnf/cli/main.py", line 170, in user_main
    errcode = main(args)
  File "/usr/lib/python3.5/site-packages/dnf/cli/main.py", line 60, in main
    return _main(base, args)
  File "/usr/lib/python3.5/site-packages/dnf/cli/main.py", line 93, in _main
    cli.configure(list(map(ucd, args)))
  File "/usr/lib/python3.5/site-packages/dnf/cli/cli.py", line 932, in configure
    self.base.init_plugins(opts.disableplugins, self)
  File "/usr/lib/python3.5/site-packages/dnf/base.py", line 226, in init_plugins
    self._plugins.run_init(self, cli)
  File "/usr/lib/python3.5/site-packages/dnf/plugin.py", line 120, in run_init
    plugin = p_cls(base, cli)
  File "/usr/lib/python3.5/site-packages/dnf-plugins/langpacks.py", line 732, in __init__
    config = self.read_config(self.base.conf, "langpacks")
TypeError: read_config() takes 2 positional arguments but 3 were given

**Comment by j-mracek** [comment]
Please can you mentioned in spec file, that the present version is incompatible with dnf-2.0

**Comment by pnemade** [comment]
Sorry for late reply as it was already decided that dnf-langpack has becoming  obsolete due to new way of installing langpacks using RPM weakdeps tag. This became invalid now.
